spring:
  application:
    name: cinema-zino-backend

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinemazino
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

jwt:
  secret: your_jwt_secret
  expiration: 3600 # in seconds
  header: Authorization
  prefix: Bearer